# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'KConnect' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'JWTDecode'
  pod 'SwiftKeychainWrapper'

  # Pods for KConnect

  target 'KConnectTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'KConnectUITests' do
    # Pods for testing
  end

end
